apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-projects
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: infra
  source:
    path: argocd_infra/projects
    repoURL: https://github.com/Mark-Rayhshtat/argo-cd-mark.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
