apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-prod
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  project: prod
  source:
    path: apps/kustomization/app1/overlays/prod
    repoURL: https://github.com/Mark-Rayhshtat/argo-cd-mark.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
