apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-prod
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-sync-running.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-sync-failed.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-health-degraded.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-deployed.slack: test-argonotif
    notifications.argoproj.io/subscribe.jenkins-on-success.jenkins: ""
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: prod
  project: prod
  source:
    path: apps/kustomization/app2/overlays/prod
    repoURL: https://github.com/Mark-Rayhshtat/argo-cd-mark.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
