apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
spec:
  description: Project
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: false
  sourceRepos:
  - https://github.com/Mark-Rayhshtat/argo-cd-mark.git
