apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-stg
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-sync-failed.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-health-degraded.slack: test-argonotif
    notifications.argoproj.io/subscribe.on-deployed.slack: test-argonotif
    notifications.argoproj.io/subscribe.jenkins-on-success.jenkins: ""
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: stg
  project: stg
  source:
    path: apps/kustomization/app2/overlays/stg
    repoURL: https://github.com/Mark-Rayhshtat/argo-cd-mark.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
