apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app2-dev-02
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: test-argonotif
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: dev
  source:
    path: apps/kustomization/app2/overlays/dev
    repoURL: https://github.com/Mark-Rayhshtat/argo-cd-mark.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
