apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1-dev
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  project: dev
  source:
    path: apps/kusromization/app1/overlays/dev
    repoURL: https://github.com/Mark-Rayhshtat/argo-cd-mark.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
